version: '3'
services:
    client:
        build:
            context: ./
            dockerfile: DockerfileClient
        tty: true
        networks:
            - service-network
    server:
        build:
            context: ./
            dockerfile: DockerfileServer
        tty: true
        networks:
            - service-network
networks:
    service-network:
        driver: bridge