version: '3'
services:
    client:
        build:
            context: ./
            dockerfile: DockerfileClient
        tty: true
        environment:
            SERVER_ADDR: server:50051
        networks:
            - service-network
        depends_on:
            server:
                condition: service_started
    server:
        build:
            context: ./
            dockerfile: DockerfileServer
        tty: true
        environment:
            PORT: 50051
        networks:
            - service-network
networks:
    service-network:
        driver: bridge